linux: &linux
  os: linux
  dist: bionic
  language: python
  env: CC=gcc-7 CXX=g++-7

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      python: "3.6"
      env: 
        - ESMF="8.1.0_beta_snapshot_36"
    - <<: *linux
      python: "3.7"
      env: 
        - ESMF="8.1.0_beta_snapshot_36"
    - <<: *linux
      python: "3.8"
      env: 
        - ESMF="8.1.0_beta_snapshot_36"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.6.10"
        - ESMF="8.1.0_beta_snapshot_36"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.7.6"
        - ESMF="8.1.0_beta_snapshot_36"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.8.2"
        - ESMF="8.1.0_beta_snapshot_36"

before_install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - git clone https://github.com/Chrismarsh/pyESMF.git
  - (cd pyESMF && git checkout $TRAVIS_BRANCH)
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(pyenv init -)"; pyenv activate esmf         ; fi
  - pip install --upgrade pip
  - cd $ESMF
  - ls -la
  - pip install .
deploy:
  provider: script
  script: cd .. && pwd && ls -la && bash ./.travis/deploy.sh